# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        import http.client

        conn = http.client.HTTPSConnection("glados.cloud")
        payload = "{\"token\":\"glados.cloud\"}"
        headers = {
          'accept': 'application/json, text/plain, */*',
          'accept-language': 'en,zh-CN;q=0.9,zh;q=0.8,zh-TW;q=0.7,ja;q=0.6',
          'content-type': 'application/json;charset=UTF-8',
          'origin': 'https://glados.cloud',
          'priority': 'u=1, i',
          'sec-ch-ua': '"Google Chrome";v="149", "Chromium";v="149", "Not)A;Brand";v="24"',
          'sec-ch-ua-mobile': '?1',
          'sec-ch-ua-platform': '"Android"',
          'sec-fetch-dest': 'empty',
          'sec-fetch-mode': 'cors',
          'sec-fetch-site': 'same-origin',
          'user-agent': 'Mozilla/5.0 (Linux; Android 15; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Mobile Safari/537.36',
          'Cookie': 'koa:sess=eyJ1c2VySWQiOjcyNDgyMiwiX2V4cGlyZSI6MTgwNzQ1Mzk5MzQxMywiX21heEFnZSI6MjU5MjAwMDAwMDB9; koa:sess.sig=ctAMRtZayE0bKxZ__A-7dHr1xqc'
        }
        conn.request("POST", "/api/user/checkin", payload, headers)
        res = conn.getresponse()
        data = res.read()
        print(data.decode("utf-8"))
